### ISSUE TITLE
Regarding Primecoin.io Repo Admin

### ISSUE THREAD

**Issue by Osamu-Yamamoto** [super3/primecoin.io#51]
Dear Shawn:

This is Osamu from Primecoin Foundation. We are doing some significant changes to Primecoin and would like to reflect those changes and our mentality on the official website. We appreciate your contribution in maintaining the website for us for these years, but we find that it may be more convenient if one of our members could have admin access to this repo to facilitate our weekly update. HarryeTian, one of our developers who has been in contact with you, would be great for that position. 

Please let me know your thoughts. My email address is osamu.yamamoto@primecoin.org.

Best
Osamu

**Comment by HarryeTian** [comment]
Ahh, Osamu did not @ me! 
What I want is just I can merge the new version of website into the primecoin.io repo and some bugs fix here and there sometime.
