### ISSUE TITLE
Website SSL

### ISSUE THREAD

**Issue by justjamesdev** [super3/primecoin.io#55]
Afternoon @super3 

Is it possible to add an SSL version of the primecoin website? Certificates are usually free now if you use LetsEncrypt. Hows the site hosted? 

SSL is required for adding primecoin to some 3rd party services such as Ledger / Trezor. 

Thanks!

**Comment by justjamesdev** [comment]
Nearly time for a yearly reminder !

**Comment by super3** [comment]
@justjamesdev Will look into it. Probably easiest to set something up with LetsEncrypt, or covert it to a static site and put it on some standard website host.

**Comment by super3** [comment]
@justjamesdev Adding it as we speak. Will be live as soon as the DNS propagates.

**Comment by super3** [comment]
@justjamesdev Done, https://primecoin.io

**Comment by justjamesdev** [comment]
Nice one Shawn, Thanks! :)
